name: gods_time
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  dio: ^5.0.2
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/roboto/RobotoMono-Italic.ttf
        - asset: assets/fonts/roboto/RobotoMono-Regular.ttf

          style: italic
    - family: Roboto Mono Bold
      fonts:
        - asset: assets/fonts/roboto/RobotoMono-Bold.ttf
        - asset: assets/fonts/roboto/RobotoMono-BoldItalic.ttf
          weight: 700
    - family: Roboto Mono Semi Bold
      fonts:
        - asset: assets/fonts/roboto/RobotoMono-SemiBold.ttf
        - asset: assets/fonts/roboto/RobotoMono-SemiBoldItalic.ttf
          style: italic
          weight: 500
    - family: Roboto Mono Light
      fonts:
        - asset: assets/fonts/roboto/RobotoMono-Light.ttf
        - asset: assets/fonts/roboto/RobotoMono-LightItalic.ttf
          style: italic
    - family: Roboto Mono Medium
      fonts:
        - asset: assets/fonts/roboto/RobotoMono-Medium.ttf
        - asset: assets/fonts/roboto/RobotoMono-MediumItalic.ttf
          style: italic
    - family: Roboto Mono Thin
      fonts:
        - asset: assets/fonts/roboto/RobotoMono-Thin.ttf
        - asset: assets/fonts/roboto/RobotoMono-ThinItalic.ttf
          style: italic
    - family: Roboto Extra Light
      fonts:
        - asset: assets/fonts/roboto/RobotoMono-ExtraLight.ttf
        - asset: assets/fonts/roboto/RobotoMono-ExtraLightItalic.ttf
          style: italic
